beton/user/views.py
# -*- coding: utf-8 -*-
import btcpay
import names
import pickle
import pprint
import random
import shutil
import tempfile
import uuid

from datetime import datetime, timedelta
from dateutil.relativedelta import *
from PIL import Image, ImageDraw, ImageFont

from flask import Blueprint, current_app, flash, g, jsonify, redirect
from flask import render_template, request, session, url_for
from flask_security import current_user, login_required, roles_accepted
from flask_uploads import UploadSet, IMAGES

from beton.extensions import cache
from beton.logger import log
from beton.user.forms import AddBannerForm, AddBannerTextForm, AddPairingTextForm, AddWebsiteForm, AddZoneForm, ChangeOffer
from beton.user.models import Banner, Basket, Campaignes, Impressions, Log, Orders, Payments, Prices, User, Websites, Zones
from beton.utils import dblogger, flash_errors

blueprint = Blueprint('user', __name__, url_prefix='/me', static_folder='../static')
images = UploadSet('images', IMAGES)


def get_randomname():
    '''protects from (unlikely) repeating campaign name'''
    while True:
        randomname = names.get_full_name()
        if Campaignes.query.filter_by(name=randomname).first() is None:
            break
    return randomname


def amiadmin():
    if current_user.has_role('admin'):
        isadmin = True
    else:
        isadmin = False
    return isadmin


def random_color():
    color = "%03x" % random.randint(0, 0xFFF)
    return "#"+str(color)


# it is safe to cache it for 10 minutes or even more
@cache.memoize(600)
def create_banner_overview(zone):
    destpath = (current_app.config.get('UPLOADED_IMAGES_DEST') +
                "/overview/zone-%s.png" % str(zone))
    dwg = Image.new(
        'RGB',
        (
            current_app.config.get('BANNER_OVERVIEW_WIDTH'),
            current_app.config.get('BANNER_OVERVIEW_HEIGHT')
        ),
        color='red'
    )

    zonedata = Zones.query.filter_by(id=zone).first()
    # font = ImageFont.load_default()

    b = ImageDraw.Draw(dwg)
    b.rectangle(
        [
            (
                zonedata.x0,
                zonedata.y0
            ),
            (
                zonedata.x1,
                zonedata.y1
            )
        ],
        fill='yellow'
    )
    b.text(
        (
            zonedata.x0+3,
            zonedata.y0+3
        ),
        str(zone),
        fill='black',

    )
    dwg.save(destpath, 'PNG')


@blueprint.url_value_preprocessor
def get_basket(endpoint, values):
    """We need basket on every view if authenticated"""
    if current_user.is_authenticated:
        try:
            basket_sql = Basket.query.filter_by(user_id=current_user.id).all()
            if basket_sql:
                g.basket = len(basket_sql)
            else:
                g.basket = 0
        except Exception as e:
            # # TODO: it might be required for minor used servers,
            # # as after 8 hours we are getting disconnected from mysqld
            # db.session.rollback()
            log.exception(e)
            pass


@blueprint.route('/me')
@login_required
def user_me():
    """Main website for logged-in user"""
    return render_template('public/home.html')


@blueprint.route('/add/bannerz', methods=['GET', 'POST'])
@login_required
def add_bannerz():
    """Add a banner."""
    form = AddBannerForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            filename = images.save(request.files['banner_image'])
            # get the width and height
            with Image.open(images.path(filename)) as img:
                width, height = img.size
            Banner.create(
                filename=filename,
                owner=current_user.id,
                url=form.banner_url.data,
                created_at=datetime.utcnow(),
                width=width,
                height=height,
                type="file",
                content="NULL",
                icon="NULL",
                comments=form.banner_comments.data
            )
            dblogger(
                current_user.id,
                "Banner %s uploaded successfully." % filename
            )
            flash('Your banner was uploaded sucessfully.', 'success')  # TODO:size
            return redirect(url_for('user.bannerz'))
        else:
            flash_errors(form)
    return render_template('users/upload_bannerz.html', form=form)


@blueprint.route('/add/text', methods=['GET', 'POST'])
@login_required
def add_text():
    """Add a text banner."""
    # TODO: fg bg colours selection in the form

    def create_image_with_text(size, text, width, height, bg, fg):
        img = Image.new('RGB', (width, height), bg)
        draw = ImageDraw.Draw(img)
        draw.text((size[0], size[1]), text, font=fnt, fill=fg)
        return img

    def roll(text, width, height, bg, fg):
        for i in range(len(text)+1):
            new_frame = create_image_with_text((0,0), text[:i], width, height, bg, fg)
            frames.append(new_frame)

    frames = []
    all_text = []
    imgdir = current_app.config.get('UPLOADED_IMAGES_DEST') + '/tmp'
    form = AddBannerTextForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.banner_submit_save.data is True:
                log.debug(form.banner_tmpimage.data)
                filename = form.banner_tmpimage.data
                shutil.copy2(imgdir + '/' + filename, current_app.config.get('UPLOADED_IMAGES_DEST') + '/' + filename)
                Banner.create(
                    filename=filename,
                    owner=current_user.id,
                    url=form.banner_url.data,
                    created_at=datetime.utcnow(),
                    width=form.banner_width.data,
                    height=form.banner_height.data,
                    type="file",
                    content="NULL",
                    icon="NULL",
                    comments=form.banner_comments.data
                )
                dblogger(
                    current_user.id,
                    "Text banner %s created successfully." % filename
                )
                flash('Banner added sucessfully.', 'success')
                return redirect(url_for('user.bannerz'))
            else:
                #fnt = ImageFont.truetype("/usr/share/fonts/truetype/freefont/FreeMono.ttf", form.banner_height.data)
                fnt = ImageFont.truetype("/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf",
                                        encoding="unic",
                                        size=form.banner_height.data - int(form.banner_height.data/10))
                all_text.append(form.banner_content_line1.data)
                if form.banner_content_line2.data:
                    all_text.append(form.banner_content_line2.data)
                if form.banner_content_line3.data:
                    all_text.append(form.banner_content_line3.data)
                if form.banner_content_line4.data:
                    all_text.append(form.banner_content_line4.data)
                if form.banner_content_line5.data:
                    all_text.append(form.banner_content_line5.data)
                width = form.banner_width.data
                height = form.banner_height.data
                bg = form.banner_bg.data
                fg = form.banner_fg.data
                [roll(text, width, height, bg, fg) for text in all_text]
                tmpf = tempfile.NamedTemporaryFile(
                    dir=imgdir,
                    suffix=".gif",
                    prefix="banner_",
                    delete=False
                )
                tmpimage = tmpf.name.split("/")[-1]
                frames[0].save(tmpf, format='GIF',
                append_images=frames[1:], save_all=True, duration=180, loop=0)
                return render_template('users/text_banner.html',
                                        form=form,
                                        tmpimage=tmpimage)
        else:
            flash_errors(form)
        return render_template('users/text_banner.html',
                               form=form,
                               tmpimage=tmpimage)
    return render_template('users/text_banner.html', form=form)


@blueprint.route('/add/zone', methods=['GET', 'POST'])
@blueprint.route('/edit/zone/<int:zoneid>', methods=['GET', 'POST'])
@roles_accepted('admin')
def add_zone(zoneid=None):
    """Add a zone."""
    all_zones = Zones.query.join(Websites).order_by(Zones.id).all()
    default_campaignes = Campaignes.query.filter_by(default=True).filter_by(active=True).join(
            Zones).join(Banner).with_entities(Zones.id, Campaignes.id, Banner.filename).all()
    urls = {}
    for x in default_campaignes:
        url = images.url(x.filename)
        urls[x.id]=images.url(x.filename)
    form = AddZoneForm()
    form.zone_website.choices = [(w.id, w.name) for w in
                                 Websites.query.order_by('name')]
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.edited.data == "yes":
                zone = Zones.query.filter_by(id=zoneid).one()
                zone.websiteid = form.zone_website.data,
                zone.name = form.zone_name.data,
                zone.comments = form.zone_comments.data,
                zone.width = form.zone_width.data,
                zone.height = form.zone_height.data,
                zone.x0 = form.zone_x0.data,
                zone.y0 = form.zone_y0.data,
                zone.x1 = form.zone_x1.data,
                zone.y1 = form.zone_y1.data,
                zone.active = form.zone_active.data
                Zones.commit()
                msg = "Zone {} updated".format(form.zone_name.data)
                dblogger(
                    current_user.id,
                    msg
                )
                log.debug(msg)
                flash('Zone updated sucessfully.', 'success')
            else:

beton/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

beton/templates/footer.html
<footer>
  <small>
  <ul class="company">
      <li>{{ site_name }}</li>
  </ul>

    <ul class="footer-nav">

        <li><a href="{{ config.CONTACT_URL }}">Contact</a></li>
    </ul>
  </small>
</footer>

beton/templates/layout.html
<!doctype html>
<!-- https://www.paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>  <html class="ie ie6 lte9 lte8 lte7"> <![endif]-->
<!--[if IE 7]>     <html class="ie ie7 lte9 lte8 lte7"> <![endif]-->
<!--[if IE 8]>     <html class="ie ie8 lte9 lte8"> <![endif]-->
<!--[if IE 9]>     <html class="ie ie9 lte9"> <![endif]-->
<!--[if gt IE 9]>  <html> <![endif]-->
<!--[if !IE]><!--> <html>             <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>
	{% block page_title %}
      		{{ config.USER_APP_NAME }}
    	{% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">
  <meta name="robots" content="nofollow" />

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script type="text/javascript" src="{{ config.SUBDIR }}/static/libs/jquery/dist/jquery.min.js"></script>

  {% assets "css_all" %}
    <link rel="stylesheet" type="text/css" href="{{ config.SUBDIR }}/static/libs/bootswatch/dist/{{ config.BOOTSWATCH }}/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

  <link rel="stylesheet" type="text/css" href="{{ config.SUBDIR }}/static/libs/dripicons2/webfont.css">

  <!--
   <link
   href="https://fonts.googleapis.com/css?family=Fresca|Tauri&amp;subset=latin-ext"
   rel="stylesheet"> 
   -->

  <!-- this part of css must be here because requires templating, not active
  during debug -->
  {% if not config['DEBUG'] %}
  <style media="screen" type="text/css">
    #loader {  
      position: fixed;  
      left: 0px;  
      top: 0px;  
      width: 100%;  
      height: 100%;  
      z-index: 9999;  
      background: url('{{ config.SUBDIR }}/static/img/loading.gif') 50% 50% no-repeat rgb(249,249,249);  
    }
  </style>
  {% endif %}

</head>
<body class="{% block body_class %}{% endblock %}">
        <div id="loader"></div>
        {# <div id="sloww">This server is slow, we know and we are working on it. At the moment just please be patient.</div> #}
{% block body %}
{% with form=form %}
{% include "nav.html" %}
{% endwith %}
{% include "public/macros.html" %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container-fluid{% endblock content_class %}">

  <div id="content" role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}

<script type="text/javascript">
{% if not config['DEBUG'] %}
    $(document).ready(function() {
        $("#loader").fadeOut(1000);
    });
{% endif %}
</script>

</body>
</html>

beton/templates/nav.html
<nav class="navbar navbar-expand-sm navbar-{{ config.NAVBAR }} bg-{{ config.NAVBAR }} rounded">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% if current_user.is_authenticated %}{{ url_for('user.user_me') }}{% else %}{{ url_for('public.home') }}{% endif %}"><span class="icon dripicons-pamphlet"></span> {{ config.USER_APP_NAME }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if current_user and current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.offer') }}"><span class="icon dripicons-checklist"></span> Our offer</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.order') }}"><span class="icon dripicons-to-do"></span> Order campaign</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.basket') }}">({% if g.basket is defined %}{{ g.basket }}{% else %}0{% endif %})<span class="icon dripicons-cart"></span> Shopping basket</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false"><span class="icon dripicons-user"></span> {{ current_user.username }}</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{{ url_for('user.campaign') }}"><span class="icon dripicons-to-do"></span> Your campaigns</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('user.bannerz') }}"><span class="icon dripicons-view-list-large"></span> Your banners</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('user.payments') }}"><span class="icon dripicons-view-list-large"></span> Your payments</a></li>
                            <li><div class="dropdown-divider"></div></li>
                            <li><a class="dropdown-item" href="{{ url_for('public.logout') }}"><span class="icon dripicons-exit"></span> Logout</a></li>
                            {% if current_user and current_user.has_role('admin') %}
                                <li><div class="dropdown-divider"></div></li>
                                <li><a class="dropdown-item" href="{{ url_for('user.listusers') }}"><span class="icon dripicons-user-group"></span> Show all users</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('user.btcpaypair') }}"><span class="icon dripicons-card"></span> Payment pairing</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('user.add_zone') }}"><span class="icon dripicons-card"></span> Zones</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('user.add_website') }}"><span class="icon dripicons-card"></span> Websites</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item"><a href="{{ url_for('security.login') }}"><span class="badge badge-pill badge-primary">Sign in</span></a>&nbsp;</li>
                    <li class="nav-item"><a href="{{ url_for('security.register') }}"><span class="badge badge-pill badge-primary">Create account</span></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>