beton/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from flask_wtf.file import FileAllowed, FileField, FileRequired
from flask_uploads import UploadSet, IMAGES
from flask_security import ConfirmRegisterForm
from wtforms import BooleanField, HiddenField, IntegerField, SelectField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, NumberRange, Required, URL

images = UploadSet('images', IMAGES)


class AddBannerForm(Form):
    """Upload banner form."""

    banner_url = StringField('URL to your advertised page - must include https:// or http://',
                             validators=[DataRequired(), Length(max=2000), URL()])
    banner_comments = StringField('Comments (optional)',
                                  validators=[Length(max=500)])
    banner_image = FileField('Banner image file',
                             validators=[FileRequired(), FileAllowed(images, 'Images only!')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddBannerForm, self).__init__(*args, **kwargs)

    # TODO: validate if size of the image is not bigger than 500kb


class AddBannerTextForm(Form):
    """Upload banner form."""

    banner_url = StringField('URL to your advertised page - must include https:// or http://',
                             validators=[DataRequired(), Length(max=2000), URL()])
    banner_width = IntegerField('Width',
                                validators=[DataRequired(), NumberRange(min=50, max=960)])
    banner_height = IntegerField('Height (50-960)',
                                validators=[DataRequired(), NumberRange(min=50, max=960)])
    banner_content_line1 = StringField('1st line',
                                 validators=[DataRequired(), Length(min=0, max=50)])
    banner_content_line2 = StringField('2nd line',
                                 validators=[Length(min=0, max=50)])
    banner_content_line3 = StringField('3rd line',
                                 validators=[Length(min=0, max=50)])
    banner_content_line4 = StringField('4th line',
                                 validators=[Length(min=0, max=50)])
    banner_content_line5 = StringField('5th line',
                                 validators=[Length(min=0, max=50)])
    banner_comments = StringField('Comments (optional)',
                                  validators=[Length(max=500)])
    banner_submit_render = SubmitField(label='render')
    banner_submit_save = SubmitField(label='save')
    banner_tmpimage = HiddenField()
    banner_bg = StringField('Background colour',
                            default='rgba(240, 255, 0, 1)',
                            validators=[DataRequired()])
    banner_fg = StringField('Text colour',
                            default='rgba(0, 0, 0, 1)',
                            validators=[DataRequired()])


    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddBannerTextForm, self).__init__(*args, **kwargs)

class AddZoneForm(Form):
    """Add zone."""

    zone_website = SelectField('Choose website:', coerce=int)

    zone_name = StringField('Zone name (10 to 100 characters)',
                            validators=[DataRequired(), Length(min=10, max=100)])
    zone_comments = StringField('Description (optional)',
                                validators=[Length(max=500)])
    zone_width = IntegerField('Width (10-1500)',
                               validators=[DataRequired(), NumberRange(min=10, max=1500)])
    zone_height = IntegerField('Height (10-1500)',
                               validators=[DataRequired(), NumberRange(min=10, max=1500)])
    zone_x0 = IntegerField('x0', validators=[NumberRange(min=0, max=1500)],
                                             default=0)
    zone_x1 = IntegerField('x1', validators=[NumberRange(min=0, max=1500)],
                                             default=0)
    zone_y0 = IntegerField('y0', validators=[NumberRange(min=0, max=1500)],
                                             default=0)
    zone_y1 = IntegerField('y1', validators=[NumberRange(min=0, max=1500)],
                                             default=0)
    zone_active = BooleanField('active', default=True)
    edited = HiddenField()

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddZoneForm, self).__init__(*args, **kwargs)


class AddWebsiteForm(Form):
    """Add website."""

    website_name = StringField('Website name (10 to 100 characters)',
                               validators=[DataRequired(), Length(min=10, max=100)])
    website_comments = StringField('Description (optional)',
                                   validators=[Length(max=500)])
    website_path = StringField('A default path for a banner',
                               validators=[DataRequired(), Length(min=5, max=100)])
    website_active = BooleanField('active', default=True)
    edited = HiddenField()

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddWebsiteForm, self).__init__(*args, **kwargs)


class AddPairingTextForm(Form):
    """Payment processor pairing form."""

    pairing_code = StringField('Type access token pairing code generated in your payment processor:',
                               validators=[DataRequired(), Length(min=7, max=7)])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(AddPairingTextForm, self).__init__(*args, **kwargs)


class ChangeOffer(Form):
    """Modify zone prices."""
    zoneprice = IntegerField('Price per day')
    zoneid = IntegerField('Zone ID')

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(ChangeOffer, self).__init__(*args, **kwargs)


class ExtendedConfirmRegisterForm(ConfirmRegisterForm):
    '''user registration'''
    username = StringField('Username', [Required()])

beton/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

beton/user/views.py
# -*- coding: utf-8 -*-
import btcpay
import names
import pickle
import pprint
import random
import shutil
import tempfile
import uuid

from datetime import datetime, timedelta
from dateutil.relativedelta import *
from PIL import Image, ImageDraw, ImageFont

from flask import Blueprint, current_app, flash, g, jsonify, redirect
from flask import render_template, request, session, url_for
from flask_security import current_user, login_required, roles_accepted
from flask_uploads import UploadSet, IMAGES

from beton.extensions import cache
from beton.logger import log
from beton.user.forms import AddBannerForm, AddBannerTextForm, AddPairingTextForm, AddWebsiteForm, AddZoneForm, ChangeOffer
from beton.user.models import Banner, Basket, Campaignes, Impressions, Log, Orders, Payments, Prices, User, Websites, Zones
from beton.utils import dblogger, flash_errors

blueprint = Blueprint('user', __name__, url_prefix='/me', static_folder='../static')
images = UploadSet('images', IMAGES)


def get_randomname():
    '''protects from (unlikely) repeating campaign name'''
    while True:
        randomname = names.get_full_name()
        if Campaignes.query.filter_by(name=randomname).first() is None:
            break
    return randomname


def amiadmin():
    if current_user.has_role('admin'):
        isadmin = True
    else:
        isadmin = False
    return isadmin


def random_color():
    color = "%03x" % random.randint(0, 0xFFF)
    return "#"+str(color)


# it is safe to cache it for 10 minutes or even more
@cache.memoize(600)
def create_banner_overview(zone):
    destpath = (current_app.config.get('UPLOADED_IMAGES_DEST') +
                "/overview/zone-%s.png" % str(zone))
    dwg = Image.new(
        'RGB',
        (
            current_app.config.get('BANNER_OVERVIEW_WIDTH'),
            current_app.config.get('BANNER_OVERVIEW_HEIGHT')
        ),
        color='red'
    )

    zonedata = Zones.query.filter_by(id=zone).first()
    # font = ImageFont.load_default()

    b = ImageDraw.Draw(dwg)
    b.rectangle(
        [
            (
                zonedata.x0,
                zonedata.y0
            ),
            (
                zonedata.x1,
                zonedata.y1
            )
        ],
        fill='yellow'
    )
    b.text(
        (
            zonedata.x0+3,
            zonedata.y0+3
        ),
        str(zone),
        fill='black',

    )
    dwg.save(destpath, 'PNG')


@blueprint.url_value_preprocessor
def get_basket(endpoint, values):
    """We need basket on every view if authenticated"""
    if current_user.is_authenticated:
        try:
            basket_sql = Basket.query.filter_by(user_id=current_user.id).all()
            if basket_sql:
                g.basket = len(basket_sql)
            else:
                g.basket = 0
        except Exception as e:
            # # TODO: it might be required for minor used servers,
            # # as after 8 hours we are getting disconnected from mysqld
            # db.session.rollback()
            log.exception(e)
            pass


@blueprint.route('/me')
@login_required
def user_me():
    """Main website for logged-in user"""
    return render_template('public/home.html')


@blueprint.route('/add/bannerz', methods=['GET', 'POST'])
@login_required
def add_bannerz():
    """Add a banner."""
    form = AddBannerForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            filename = images.save(request.files['banner_image'])
            # get the width and height
            with Image.open(images.path(filename)) as img:
                width, height = img.size
            Banner.create(
                filename=filename,
                owner=current_user.id,
                url=form.banner_url.data,
                created_at=datetime.utcnow(),
                width=width,
                height=height,
                type="file",
                content="NULL",
                icon="NULL",
                comments=form.banner_comments.data
            )
            dblogger(
                current_user.id,
                "Banner %s uploaded successfully." % filename
            )
            flash('Your banner was uploaded sucessfully.', 'success')  # TODO:size
            return redirect(url_for('user.bannerz'))
        else:
            flash_errors(form)
    return render_template('users/upload_bannerz.html', form=form)


@blueprint.route('/add/text', methods=['GET', 'POST'])
@login_required
def add_text():
    """Add a text banner."""
    # TODO: fg bg colours selection in the form

    def create_image_with_text(size, text, width, height, bg, fg):
        img = Image.new('RGB', (width, height), bg)
        draw = ImageDraw.Draw(img)
        draw.text((size[0], size[1]), text, font=fnt, fill=fg)
        return img

    def roll(text, width, height, bg, fg):
        for i in range(len(text)+1):
            new_frame = create_image_with_text((0,0), text[:i], width, height, bg, fg)
            frames.append(new_frame)

    frames = []
    all_text = []
    imgdir = current_app.config.get('UPLOADED_IMAGES_DEST') + '/tmp'
    form = AddBannerTextForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.banner_submit_save.data is True:
                log.debug(form.banner_tmpimage.data)
                filename = form.banner_tmpimage.data
                shutil.copy2(imgdir + '/' + filename, current_app.config.get('UPLOADED_IMAGES_DEST') + '/' + filename)
                Banner.create(
                    filename=filename,
                    owner=current_user.id,
                    url=form.banner_url.data,
                    created_at=datetime.utcnow(),
                    width=form.banner_width.data,
                    height=form.banner_height.data,
                    type="file",
                    content="NULL",
                    icon="NULL",
                    comments=form.banner_comments.data
                )
                dblogger(
                    current_user.id,
                    "Text banner %s created successfully." % filename
                )
                flash('Banner added sucessfully.', 'success')
                return redirect(url_for('user.bannerz'))
            else:
                #fnt = ImageFont.truetype("/usr/share/fonts/truetype/freefont/FreeMono.ttf", form.banner_height.data)
                fnt = ImageFont.truetype("/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf",
                                        encoding="unic",
                                        size=form.banner_height.data - int(form.banner_height.data/10))
                all_text.append(form.banner_content_line1.data)
                if form.banner_content_line2.data:
                    all_text.append(form.banner_content_line2.data)
                if form.banner_content_line3.data:
                    all_text.append(form.banner_content_line3.data)
                if form.banner_content_line4.data:
                    all_text.append(form.banner_content_line4.data)
                if form.banner_content_line5.data:
                    all_text.append(form.banner_content_line5.data)
                width = form.banner_width.data
                height = form.banner_height.data
                bg = form.banner_bg.data
                fg = form.banner_fg.data
                [roll(text, width, height, bg, fg) for text in all_text]
                tmpf = tempfile.NamedTemporaryFile(
                    dir=imgdir,
                    suffix=".gif",
                    prefix="banner_",
                    delete=False
                )
                tmpimage = tmpf.name.split("/")[-1]
                frames[0].save(tmpf, format='GIF',
                append_images=frames[1:], save_all=True, duration=180, loop=0)
                return render_template('users/text_banner.html',
                                        form=form,
                                        tmpimage=tmpimage)
        else:
            flash_errors(form)
        return render_template('users/text_banner.html',
                               form=form,
                               tmpimage=tmpimage)
    return render_template('users/text_banner.html', form=form)


@blueprint.route('/add/zone', methods=['GET', 'POST'])
@blueprint.route('/edit/zone/<int:zoneid>', methods=['GET', 'POST'])
@roles_accepted('admin')
def add_zone(zoneid=None):
    """Add a zone."""
    all_zones = Zones.query.join(Websites).order_by(Zones.id).all()
    default_campaignes = Campaignes.query.filter_by(default=True).filter_by(active=True).join(
            Zones).join(Banner).with_entities(Zones.id, Campaignes.id, Banner.filename).all()
    urls = {}
    for x in default_campaignes:
        url = images.url(x.filename)
        urls[x.id]=images.url(x.filename)
    form = AddZoneForm()
    form.zone_website.choices = [(w.id, w.name) for w in
                                 Websites.query.order_by('name')]
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.edited.data == "yes":
                zone = Zones.query.filter_by(id=zoneid).one()
                zone.websiteid = form.zone_website.data,
                zone.name = form.zone_name.data,
                zone.comments = form.zone_comments.data,
                zone.width = form.zone_width.data,
                zone.height = form.zone_height.data,
                zone.x0 = form.zone_x0.data,
                zone.y0 = form.zone_y0.data,
                zone.x1 = form.zone_x1.data,
                zone.y1 = form.zone_y1.data,
                zone.active = form.zone_active.data
                Zones.commit()
                msg = "Zone {} updated".format(form.zone_name.data)
                dblogger(
                    current_user.id,
                    msg
                )
                log.debug(msg)
                flash('Zone updated sucessfully.', 'success')
            else:

beton/templates/users/bannerz.html
{% extends "layout.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Your banners, {{ current_user.username }}</h1>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <p><a class="btn btn-primary btn-lg" role="button" href="{{ url_for('user.add_bannerz') }}">Upload your ready banner</a></p>
                <span class="label label-info">
                    Your image banner must have exactly the same size as the
                    zone you want to put it in - or smaller.</span>
            </div>
            {% if config.BANNERS_TEXT %}
            <div class="col-sm-6 col-xs-12">
                <p><a class="btn btn-primary btn-lg" role="button" href="{{ url_for('user.add_text') }}">Add a new text banner</a></p>
                <span class="label label-info">
                    You are able to create a simple text animated banner.
                    </span>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="card-columns">
        {% for banner in all_banners|reverse %}
            <div class="card border-light">
                <div class="card-header">
                    Banner #{{ banner.id }}
                    {% if banner.type == "text" %}
                        <span class="badge badge-pill badge-info">TEXT</span>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% if banner.type == "text" %}
                        <div class="card-header">
                            <i class="{{ banner.icon }}" aria-hidden="true"></i>&nbsp;
                            {{ banner.content }}
                        </div>
                    {% else %}
                    <div class="thumbnail">
                        {% for url in all_urls %}
                            {% if url[0] == banner.id %}
                                <img src="{{ url[1] }}" class="img-thumbnail">
                                {#% break %#}
                            {% endif %}
                            {% endfor %}
                    </div>
                    {% endif %}
                    <div class="card-text">
                        <div id="created_at">{{ banner.created_at }}</div>
                        <div id="url">{{ banner.url }}</div>
                        {% if banner.type == "file" %}
                            <div id="size">{{ banner.width }} x {{ banner.height }}</div>
                        {% endif %}
                        <div id="comment">{{ banner.comment }}</div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ url_for('user.clear_banner', banner_id=banner.id) }}"
                        class="btn btn-danger btn-sm btn-block">Delete this banner</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

beton/templates/users/campaign-elements.html
<div class="card border-light">
    <div class="card-header">
        <h5><a href="{{ url_for('user.campaign', campaign_id=campaign[0].id) }}">#{{ campaign[0].id }} {{ campaign[0].name }}</a></h5>
        {% if campaign.type == "text" %}
            <div class="card-header">
            <i class="{{ campaign.icon }}" aria-hidden="true"></i>&nbsp;
            {{ campaign.content }}
        </div>
        {% else %}
            <img class="img-thumbnail thumbmax" 
                src="{{ urls[campaign[0].id] }}"
                alt="[B{{ campaign[0].id }}]">
        {% endif %}
        <p class="text-muted">Zone #{{ campaign[0].zoneid }}</p>
        <p class="text-muted">{{ campaign[3].comments }}</p>
    </div>
    <div class="card-body">
        <div class="card-text">
            <p>
                <b>From:</b> {{ campaign[0].begins_at.strftime('%Y-%m-%d') }}<br/>
                <b>To:</b> {{ campaign[0].stops_at.strftime('%Y-%m-%d') }}
            </p>

            {% if campaign[1].confirmed_at != datemin %}
                {% if campaign[0].begins_at <= now %}
                    <p><b>Impressions:</b>&nbsp;
                        {{ campaign[6].impressions }}
                    </p>
                {% else %}
                    <p>Campaign starts in 
                        {{ (campaign[0].begins_at - now).days + 1}}
                            day(s)
                    </p>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="card-footer">
        <a href="{{ url_for('user.campaign', campaign_id=campaign[0].id) }}"
            class="btn btn-info btn-sm btn-block">More details</a>
    </div>
</div>

beton/templates/users/order.html
{% extends "layout.html" %}
{% block content %}
{% if step == 'chose-banner' %}
    <div class="jumbotron">
        <h1>Select a banner, {{ current_user.username }}</h1>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <p class="lead">Select a banner for your new campaign, please</p>
                <p>or <a class="btn btn-primary" role="button"
                        href="{{ url_for('user.add_bannerz') }}">Add a new banner</a></p>
            </div>
            <div class="col-sm-6 col-xs-12">
                <h4>Alternatively</h4>
                <form action="{{ url_for('user.order')  }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <button type="submit" name="submit" class="btn btn-danger"
                        value="cancel">Cancel this campaign</button>
                </form>
            </div>
        </div>
    </div>
    <div class="card-columns">
        {% for banner in all_banners|reverse %}
            <div class="card border-light">
                <div class="card-header">
                    Banner #{{ banner.id }}
                </div>
                <div class="card-body">
                    {% if banner.type == "text" %}
                        <div class="card-header">
                            <span class="{{ banner.icon }}" aria-hidden="true"></span>&nbsp; {{ banner.content }}
                        </div>
                    {% else %}
                        <div class="thumbnail">
                            {% for url in all_urls %}
                                {% if url[0] == banner.id %}
                                    <img src="{{ url[1] }}" class="img-thumbnail">
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                        <div class="caption">
                            <div id="created_at">{{ banner.created_at }}</div>
                            <div id="url">{{ banner.url }}</div>
                            {% if banner.type != "text" %}
                                <div id="size"><p>size: {{ banner.width }}x{{ banner.height }}</p></div>
                            {% endif %}
                            <div id="comment">{{ banner.comment }}</div>
                        </div>
                        <br/>
                        <form action="{{ url_for('user.order') }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <input type="hidden" name="banner_id" value="{{ banner.id }}">
                            <input type="hidden" name="step" value="chose-zone">
                            <button type="submit" value="chose-zone" class="btn
                                btn-primary btn-block">Choose this banner</button>
                        </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% elif step == "chose-zone" %}
    <div class="jumbotron">
        <h1>Select the zone, {{ current_user.username }}</h1>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <p class="lead">In which zone do you want to display this banner?</p>
                {% if banner.type == "text" %}
                    <div class="card-header">
                        <i class="{{ banner.icon }}" aria-hidden="true"></i>&nbsp;{{ banner.content }}
                    </div>
                {% else %}
                    <p><img class="img-thumbnail thumbmax" src="{{ image_url }}"></p>
                {% endif %}
            </div>
            <div class="col-sm-6 col-xs-12">
                <h4>Alternatively</h4>
                    <form action="{{ url_for('user.order')  }}" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <button type="submit" name="submit" class="btn btn-danger"
                            value="cancel">Cancel this campaign</button>
                    </form>
            </div>
        </div>
    </div>
    {% if all_zones %}
        <div id="card-colums">
            {% for zone in all_zones %}
                <div class="card border-light">
                    <div class="card-header">
                        Zone #{{ zone[0].id }}
                    </div>
                    <div class="card-body">
                        <div id="zonewebsite">{{ zone.name }}</div>
                        <div id="zonename">{{ zone[0].name }}</div>
                        <div id="zonecomments">{{ zone[0].comments }}</div>
                        <div id="zoneprice"><p>price: {{ zone.dayprice / 100 }} {{ zone.fiat }}/day</p></div>
                        {% if banner.type == "file" %}
                            <div id="zonesizetxt"><p>size: {{ zone[0].width }}x{{ zone[0].height }}</p></div>
                            <div id="zonesize"><img src="holder.js/{{ zone[0].width}}x{{ zone[0].height }}" class="img-thumbnail thumbmax"></div>
                        {% endif %}
                        <form action="{{ url_for('user.order') }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <input type="hidden" name="banner_id" value="{{ banner.id }}" />
                            <input type="hidden" name="zone_id" value="{{ zone[0].id }}" />
                            <input type="hidden" name="zone_name" value="{{ zone[0].name }}" />
                            <input type="hidden" name="step" value="chose-date" />
                            <hr>
                            <button type="submit" name="submit" value="chose-date" class="btn
                                btn-primary">Choose this zone</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no zones able to fit your banner. Check 
            <a href="{{ url_for('user.offer') }}">our offer</a> again, please.</p>
    {% endif %}
{% elif step == "chose-date" %}
    <div class="jumbotron">
        <h1>Select dates, {{ current_user.username }}</h1>
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <p class="lead">Please select time period for this banner</p>
                {% if banner.type == "text" %}
                    <div class="card-header">
                        <i class="{{ banner.icon  }}" aria-hidden="true"></i>&nbsp;{{ banner.content}}
                    </div>
                {% else %}
                    <p><img class="img-thumbnail thumbmax" src="{{ image_url }}"></p>
                {% endif %}
            </div>
            <div class="col-sm-6 col-xs-12">
                <h4>Alternatively</h4>
                <form action="{{ url_for('user.order')  }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <button type="submit" name="submit" class="btn btn-danger"
                        value="cancel">Cancel this campaign</button>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <form action="{{ url_for('user.order') }}" method="post">
                <div class="row">
                    <div class="col-sm-6 col-xs-12"><p>Start:</p>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>&nbsp;
                            </div>
                        <input type="text" id="datestart" name="datestart" value="" />
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-12"><p>Finish:</p>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>&nbsp;
                            </div>
                        <input type="text" id="datend" name="datend" value="" />
                        </div>
                    </div>
                </div>
                <br/><br/>
                <div class="row">
                    <div class="col">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        <input type="hidden" name="banner_id" value="{{ banner_id }}" />
                        <input type="hidden" name="zone_id" value="{{ zone_id }}" />
                        <input type="hidden" name="zone_name" value="{{ zone_name }}" />
                        <input type="hidden" name="step" value="order" />
                        <button type="submit" name="submit" value="order" class="btn
                            btn-primary">Confirm dates and add to your shopping basket</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-6 col-xs-12">
            <h3>All recent campaigns in this zone, for your conveniance</h3>
            <div id="calendar"></div>
        </div>
    </div>
    <script>
        var events_source = "{{ config.SUBDIR }}/api/all_campaigns_in_zone/{{ zone_id }}";
    </script>
{% elif step == "order" %}
    <div class="jumbotron">
        <h1>Campaign added, {{ current_user.username }}</h1>
                <p>Carefully check your order. If it is not correct, remove it
                    from your <a href="{{ url_for('user.basket') }}">shopping basket</a>. If everything is OK, pay for your basket
                    or order another campaign and pay for all of them later.
                </p>
                <a href="{{ url_for('user.order') }}" class="btn btn-info">Order another campaign and pay
                    later</a>
                or 
                <a href="{{ url_for('user.basket') }}" class="btn btn-info">See your
                    basket and pay</a>
    </div>
    <h2>Statement of facts</h2>
    <div class="row">
        <div class="col">
            <p>You want to have a campaign with banner #{{ banner_id }}</p>
            {% if banner.type == "text" %}
            <div class="card-header">
                <i class="{{ banner.icon  }}" aria-hidden="true"></i>&nbsp;{{ banner.content }}
            </div>
            {% else %}
                <p><img class="img-thumbnail thumbmax" src="{{ image_url }}"></p>
            {% endif %}
            <p>for period: {{ datestart }} -  {{ datend }}.</p>
        </div>
        <div class="col">
            <h3>Calculations</h3>
            <p>It's {{ days+1 }} day(s) alltogether, each day for: {{ dayprice/100 }} {{ config.FIAT }}</p>
            <h4><span class="badge badge-info">Total is: {{ dayprice/100*(days+1) }} {{ config.FIAT }}</span></h4>
        </div>
    </div>

{% endif %}
{% endblock %}

{% block js %}
{% if step == "chose-date" %}
    {% include "users/order-chose-date.html" %}
{% endif %}
{% endblock %}